# Generated by Django 6.0.2 on 2026-03-31 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0002_alter_position_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Voting.school'),
        ),
    ]
