# Generated by Django 6.0.2 on 2026-04-27 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0004_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender_allowed', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], default='B', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='gender_requirement',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='position',
            name='residency_requirement',
            field=models.CharField(choices=[('All', 'All'), ('R', 'Resident'), ('NR', 'Non-Resident')], default='All', max_length=3),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='residency_status',
            field=models.CharField(choices=[('R', 'Resident'), ('NR', 'Non-Resident')], default='NR', max_length=2),
        ),
        migrations.AddField(
            model_name='position',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Voting.hall'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Voting.hall'),
        ),
    ]
